@extends('layouts.app')
@section('title', ($lesson->exists ? 'Modifica' : 'Registra').' lezione · Lezioni in ordine')
@section('content')
<section class="page-heading"><a class="back-link" href="{{ route('lezioni.index') }}">← Lezioni</a><p class="eyebrow">{{ $lesson->exists ? 'Modifica registro' : 'Nuova registrazione' }}</p><h1>{{ $lesson->exists ? 'Dettagli della lezione' : 'Registra una lezione' }}</h1></section>
<form class="form-card" method="post" action="{{ $lesson->exists ? route('lezioni.update', $lesson) : route('lezioni.store') }}">@csrf @if($lesson->exists)@method('put')@endif
    <fieldset><legend>Lezione</legend><div class="form-grid three"><label>Studente<select name="studente_id" id="studentSelect" required><option value="">Seleziona…</option>@foreach($students as $student)<option value="{{ $student->id }}" data-rate="{{ $student->tariffa_oraria }}" @selected(old('studente_id', $lesson->studente_id) === $student->id)>{{ $student->nome_completo }}{{ $student->attivo ? '' : ' · non attivo' }}</option>@endforeach</select></label><label>Data<input type="date" name="data" value="{{ old('data', optional($lesson->data)->format('Y-m-d')) }}" required></label><label>Stato<select name="stato" id="lessonStatus" required>@foreach(['programmata'=>'Programmata','svolta'=>'Svolta','annullata'=>'Annullata','non_svolta'=>'Non svolta'] as $value=>$label)<option value="{{ $value }}" @selected(old('stato', $lesson->stato) === $value)>{{ $label }}</option>@endforeach</select></label><label>Ora inizio<input type="time" name="ora_inizio" value="{{ old('ora_inizio', $lesson->ora_inizio ? substr($lesson->ora_inizio,0,5) : '') }}" required></label><label>Ora fine<input type="time" name="ora_fine" value="{{ old('ora_fine', $lesson->ora_fine ? substr($lesson->ora_fine,0,5) : '') }}" required></label><label>Tariffa applicata (€ / h)<input type="number" id="lessonRate" name="tariffa_oraria_applicata" min="0" step="0.01" value="{{ old('tariffa_oraria_applicata', $lesson->tariffa_oraria_applicata) }}" placeholder="Tariffa dello studente"></label></div><label>Argomento<textarea name="argomento" rows="3" placeholder="Cosa avete affrontato?">{{ old('argomento', $lesson->argomento) }}</textarea></label><label>Note<textarea name="note" rows="2">{{ old('note', $lesson->note) }}</textarea></label></fieldset>
    <fieldset id="calendarFields"><legend>Google Calendar</legend><label class="check"><input type="checkbox" id="calendarToggle" name="add_to_google_calendar" value="1" @checked(old('add_to_google_calendar', (bool) $lesson->google_calendar_event_id))> {{ $lesson->google_calendar_event_id ? 'Aggiorna l’evento collegato' : 'Aggiungi questa lezione a Google Calendar' }}</label><small class="field-help">Disponibile per le lezioni programmate. Se l’evento è già collegato, viene aggiornato senza creare duplicati.</small>@if($lesson->google_calendar_event_url)<a class="calendar-link" href="{{ $lesson->google_calendar_event_url }}" target="_blank" rel="noopener noreferrer">Apri l’evento su Google Calendar ↗</a>@endif</fieldset>
    <fieldset><legend>Pagamento e fatturazione</legend><label class="check"><input type="checkbox" name="da_fatturare" value="1" @checked(old('da_fatturare', $lesson->exists ? $lesson->da_fatturare : true))> Questa lezione è da fatturare</label><small class="field-help">Disattiva il flag per lezioni gratuite, di prova o che non devono entrare nel conteggio “Da fatturare”.</small><label class="check"><input type="checkbox" id="invoicedToggle" name="fatturata" value="1" @checked(old('fatturata', $lesson->fatturata))> Lezione già fatturata</label><div id="invoiceFields" class="form-grid three"><label>Numero fattura<input name="numero_fattura" value="{{ old('numero_fattura', $lesson->numero_fattura) }}"></label><label>Data fattura<input type="date" name="data_fattura" value="{{ old('data_fattura', optional($lesson->data_fattura)->format('Y-m-d')) }}"></label><label>Stato fattura<select name="stato_fattura"><option value="">Seleziona…</option>@foreach(['emessa','inviata','pagata','scaduta','annullata'] as $status)<option value="{{ $status }}" @selected(old('stato_fattura', $lesson->stato_fattura) === $status)>{{ ucfirst($status) }}</option>@endforeach</select></label></div><label class="narrow">Data pagamento<input type="date" name="data_pagamento" value="{{ old('data_pagamento', optional($lesson->data_pagamento)->format('Y-m-d')) }}"><small>Compilandola la fattura viene segnata automaticamente come pagata.</small></label></fieldset>
    <div class="form-actions"><a class="button ghost" href="{{ route('lezioni.index') }}">Annulla</a><button class="button primary">{{ $lesson->exists ? 'Salva modifiche' : 'Registra lezione' }}</button></div>
</form>
@if($lesson->exists)<form class="danger-zone" method="post" action="{{ route('lezioni.destroy', $lesson) }}" data-confirm="Eliminare definitivamente questa lezione?">@csrf @method('delete')<button class="link-danger">Elimina lezione</button></form>@endif
@endsection
