@extends('layouts.app')
@section('title', 'Lezioni · Lezioni in ordine')
@section('content')
<section class="page-heading split"><div><p class="eyebrow">Registro</p><h1>Lezioni</h1><p>Lo storico completo, dal programma al pagamento.</p></div><a class="button primary" href="{{ route('lezioni.create') }}">＋ Registra lezione</a></section>
<form class="filter-bar filters" method="get"><label>Studente<select name="studente_id"><option value="">Tutti</option>@foreach($students as $student)<option value="{{ $student->id }}" @selected(request('studente_id') === $student->id)>{{ $student->nome_completo }}</option>@endforeach</select></label><label>Stato<select name="stato"><option value="">Tutti</option>@foreach(['programmata','svolta','annullata','non_svolta'] as $status)<option value="{{ $status }}" @selected(request('stato') === $status)>{{ ucfirst(str_replace('_',' ', $status)) }}</option>@endforeach</select></label><label>Pagamento<select name="pagamento"><option value="">Tutti</option><option value="pagata" @selected(request('pagamento') === 'pagata')>Pagata</option><option value="da_pagare" @selected(request('pagamento') === 'da_pagare')>Da pagare</option></select></label><label>Dal<input type="date" name="dal" value="{{ request('dal') }}"></label><label>Al<input type="date" name="al" value="{{ request('al') }}"></label><button class="button secondary">Filtra</button><a class="text-link" href="{{ route('lezioni.index') }}">Azzera</a></form>
<div class="table-card"><table><thead><tr><th>Data e ora</th><th>Studente</th><th>Argomento</th><th>Durata</th><th>Importo</th><th>Lezione</th><th>Pagamento</th><th></th></tr></thead><tbody>
@forelse($lessons as $lesson)<tr><td><strong>{{ $lesson->data->format('d/m/Y') }}</strong><small>{{ substr($lesson->ora_inizio,0,5) }}–{{ substr($lesson->ora_fine,0,5) }}</small></td><td>{{ $lesson->student->nome_completo }}</td><td class="topic">{{ $lesson->argomento ?: '—' }}</td><td>{{ number_format($lesson->durata_ore, 1, ',', '.') }} h</td><td>€ {{ number_format($lesson->importo, 2, ',', '.') }}</td><td><span class="status {{ $lesson->stato }}">{{ str_replace('_',' ', $lesson->stato) }}</span></td><td>@if($lesson->data_pagamento)<span class="status svolta">pagata</span><small>{{ $lesson->data_pagamento->format('d/m/Y') }}</small>@elseif($lesson->stato === 'svolta')<span class="status non_svolta">da pagare</span>@else<span class="muted">—</span>@endif</td><td class="actions"><a href="{{ route('lezioni.edit', $lesson) }}">Modifica</a></td></tr>@empty<tr><td colspan="8" class="empty-state">Nessuna lezione trovata.</td></tr>@endforelse
</tbody></table></div>{{ $lessons->links('pagination::simple-default') }}
@endsection
