@extends('layouts.app')
@section('title', ($student->exists ? 'Modifica' : 'Nuovo').' studente · Lezioni in ordine')
@section('content')
<section class="page-heading"><a class="back-link" href="{{ route('studenti.index') }}">← Studenti</a><p class="eyebrow">{{ $student->exists ? 'Modifica anagrafica' : 'Nuova anagrafica' }}</p><h1>{{ $student->exists ? $student->nome_completo : 'Aggiungi uno studente' }}</h1></section>
<form class="form-card" method="post" action="{{ $student->exists ? route('studenti.update', $student) : route('studenti.store') }}">@csrf @if($student->exists)@method('put')@endif
    <fieldset><legend>Dati dello studente</legend><div class="form-grid"><label>Nome<input name="nome" value="{{ old('nome', $student->nome) }}" required></label><label>Cognome<input name="cognome" value="{{ old('cognome', $student->cognome) }}" required></label><label>Anno di ingresso<input type="number" name="anno_ingresso" min="2000" max="{{ now()->year + 1 }}" value="{{ old('anno_ingresso', $student->anno_ingresso ?: now()->year) }}" required></label><label>Tariffa oraria (€)<input type="number" name="tariffa_oraria" min="0" step="0.01" value="{{ old('tariffa_oraria', $student->tariffa_oraria) }}" required></label></div><label class="check"><input type="checkbox" name="attivo" value="1" @checked(old('attivo', $student->exists ? $student->attivo : true))> Studente attivo</label></fieldset>
    <fieldset><legend>Informazioni di fatturazione <small>pagante</small></legend><div class="form-grid"><label>Nome<input name="pagante_nome" value="{{ old('pagante_nome', $student->pagante_nome) }}"></label><label>Cognome<input name="pagante_cognome" value="{{ old('pagante_cognome', $student->pagante_cognome) }}"></label><label>Codice fiscale<input name="pagante_codice_fiscale" maxlength="16" value="{{ old('pagante_codice_fiscale', $student->pagante_codice_fiscale) }}"></label><label>Indirizzo<input name="pagante_indirizzo" value="{{ old('pagante_indirizzo', $student->pagante_indirizzo) }}"></label></div></fieldset>
    <div class="form-actions"><a class="button ghost" href="{{ route('studenti.index') }}">Annulla</a><button class="button primary">{{ $student->exists ? 'Salva modifiche' : 'Aggiungi studente' }}</button></div>
</form>
@if($student->exists)<form class="danger-zone" method="post" action="{{ route('studenti.destroy', $student) }}" data-confirm="Eliminare definitivamente questo studente?">@csrf @method('delete')<button class="link-danger">Elimina studente</button></form>@endif
@endsection
