@extends('layouts.app')
@section('title', 'Studenti · Lezioni in ordine')
@section('content')
<section class="page-heading split"><div><p class="eyebrow">Rubrica</p><h1>Studenti</h1><p>Tariffe e informazioni del pagante sempre aggiornate.</p></div><a class="button primary" href="{{ route('studenti.create') }}">＋ Nuovo studente</a></section>
<form class="filter-bar" method="get"><label class="grow">Cerca<input type="search" name="q" value="{{ request('q') }}" placeholder="Nome o cognome"></label><button class="button secondary">Cerca</button></form>
<div class="table-card"><table><thead><tr><th>Studente</th><th>Ingresso</th><th>Tariffa</th><th>Lezioni</th><th>Stato</th><th>Registro Excel</th><th></th></tr></thead><tbody>
@forelse($students as $student)<tr><td><strong>{{ $student->nome_completo }}</strong><small>{{ $student->pagante_codice_fiscale ?: 'Dati pagante non completi' }}</small></td><td>{{ $student->anno_ingresso }}</td><td>€ {{ number_format($student->tariffa_oraria, 2, ',', '.') }}/h</td><td>{{ $student->lessons_count }}</td><td><span class="status {{ $student->attivo ? 'svolta' : 'annullata' }}">{{ $student->attivo ? 'attivo' : 'non attivo' }}</span></td><td><form class="export-form" method="get" action="{{ route('studenti.export', $student) }}"><select name="anno" aria-label="Anno scolastico">@foreach($academicYears as $year)<option value="{{ $year }}" @selected($year === $academicStart)>{{ $year }}/{{ $year + 1 }}</option>@endforeach</select><button class="button secondary" title="Scarica Excel">Scarica .xlsx</button></form></td><td class="actions"><a href="{{ route('lezioni.create', ['studente_id' => $student->id]) }}" title="Aggiungi lezione">＋</a><a href="{{ route('studenti.edit', $student) }}">Modifica</a></td></tr>@empty<tr><td colspan="7" class="empty-state">Nessuno studente trovato.</td></tr>@endforelse
</tbody></table></div>{{ $students->links('pagination::simple-default') }}
@endsection
